stages:
  prepare:
    cmd: uv run python src/data/prepare_data.py
    deps:
      - src/data/prepare_data.py
      - data/raw/train.csv
    params:
      - conf/dataset/default.yaml:
          - test_size
          - random_state
    outs:
      - data/processed/train.csv
      - data/processed/val.csv

  train:
    cmd: uv run python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/processed/train.csv
      - data/processed/val.csv
    params:
      - conf/dataset/default.yaml:
          - target
          - numeric_features
          - categorical_features
      - conf/model/default.yaml:
          - logistic_regression.max_iter
          - random_forest.n_estimators
          - random_forest.random_state
    outs:
      - models/best_model.pkl