# @package dataset

train_path: data/raw/train.csv
processed_train_path: data/processed/train.csv
processed_val_path: data/processed/val.csv

target: Survived

numeric_features:
  - Age
  - Fare
  - SibSp
  - Parch

categorical_features:
  - Embarked
  - Sex
  - Pclass

test_size: 0.2
random_state: 42
